hue:
  url: http://192.168.178.20/api
  user: 2n96zajthH6hi2HLRfShgrYGft2rgQcXO0VupveP
  groups: [7, 10]
  duration: 2
sunrise:
  url: https://api.sunrise-sunset.org
  latitude: 53.7149877
  longitude: -6.3524183
ring:
  token: eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzcxMjczNTYsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6OTkxMDkyMywicm5kIjoiWWRhSVRxeUt3U2ZXaGciLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.qfrCfhdXQd76U5K61VL9VbMlXWtCBPxy9VYOQfeLBJvxQlDx4_jMTAa4u8biUu4N_96ET9hz4M2CvfScZb7ZKw
